### ISSUE TITLE
Unsafe assignment of any value should be warning instead of error

### ISSUE THREAD

**Issue by xanderjl** [strangelove-ventures/style-guide#2]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/25848639/187787333-273db3f1-006d-4898-84b8-ade6c7ca2968.png">

In this example, we have no clear types coming from a third-party package. The type `any` was used as the preview object is a bit of a black box. I vote we opt to warn users vs erroring out completely.

**Comment by grikomsn** [comment]
https://github.com/strangelove-ventures/style-guide/commit/b6c009a5a9ec7a6eb431fa44f7608b465280ea8d
